before:
  hooks:
    - go mod tidy
    - sudo apt update
    - sudo apt install libx11-dev
    - sudo apt install xorg-dev
    - sudo apt install libxtst-dev libpng++-dev
    # Event:
    - sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev
    - sudo apt install libxkbcommon-dev
    # Clipboard:
    - sudo apt install xsel
    - sudo apt install xclip
    # Other to windows
    - sudo apt install gcc-multilib
    - sudo apt install gcc-mingw-w64
    - sudo apt install libz-mingw-w64-dev

builds:
  - binary: goldenDictHelperServer
    main: .
    env:
      - CGO_ENABLED=1
      - >-
        {{- if eq .Os "windows" }}
          {{- if eq .Arch "amd64" }}CC=x86_64-w64-mingw32-gcc{{- end }}
          {{- if eq .Arch "amd64" }}CXX=x86_64-w64-mingw32-g+{{- end }}
        {{- end }}
    goos:
      - linux
      - windows
    #      - darwin
    goarch:
      - amd64
#    ignore:
#      - goos: windows
#        goarch: arm64

checksum:
  name_template: "checksums.txt"

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}macos_
      {{- else }}{{ .Os }}_{{ end }}
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else if eq .Arch "arm64" }}aarch64
      {{- else if eq .Arch "arm" }}armv{{ .Arm }}
      {{- else }}{{ .Arch }}{{ end }}
    wrap_in_directory: true
    format_overrides:
      - goos: windows
        format: zip
    builds_info:
      group: root
      owner: root
